### ISSUE TITLE
Error 'y' and 'n' is not defined. 

### ISSUE THREAD

**Issue by FredBabino** [wuisawesome/TriviaCrackGod#1]
When playing in "duel" challenges against random or friends it asks to whether or not to answer all questions; answering "y" or "n" creates an error such as the one listed below.

(1) marlana.hodges NORMAL PENDING_APPROVAL
Select a game to win: 1
Answer all questions? (Y/N)y

Traceback (most recent call last):
  File "/Users/Desktop/Trivia Crack/TriviaCrack.py", line 130, in <module>
    main()
  File "/Users/Desktop/Trivia Crack/TriviaCrack.py", line 124, in main
    play_game(g,loop=True if (input("Answer all questions? (Y/N)")+" ")[0].lower()=='y' else False)
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined

**Comment by robertquitt** [comment]
What version of Python are you using? This script was made and tested for python 3. I should be able to change it to work for both versions soon.

**Comment by robertquitt** [comment]
To fix this issue for you you will have to replace input with raw_input. I will make a fix soon.

**Comment by FredBabino** [comment]
python 2.7.9

**Comment by imsnayer** [comment]
Error regarding the JSON reading when trying to find games.
"ValueError: No JSON object could be decoded"
